---
- hosts: all
  become: true
  vars:
    check_munge: false
    slurm_config_file: "../resources/slurm-basic-config.conf"
  tasks:
    - name: General Setup
      include: setup-common.yaml

    - name: Copy vagrant user public key to authorized keys
      blockinfile:
        path: /home/vagrant/.ssh/authorized_keys
        block: "{{ lookup('file', '../shared/creds/vagrant-head.pub') }}"

    - name: Copy munge key to expected location
      become_user: munge
      copy:
        remote_src: yes
        src: /shared/creds/munge.key
        dest: /etc/munge/munge.key
      notify:
        - restart munge service

    - name: Secure munge key
      file:
        path: /etc/munge/munge.key
        mode: '0600'
        owner: munge
      notify:
        - restart munge service

    - name: Enable munge service
      systemd:
        name: munge.service
        enabled: yes
      notify:
        - start munge service

  handlers:
    - name: start munge service
      systemd:
        name: munge.service
        state: started

    - name: restart munge service
      systemd:
        name: munge.service
        state: restarted

- hosts: all
  become: true
  tasks:
    - name: Patch Slurm Cgroup Integration
      blockinfile:
        path: /etc/slurm/cgroup.conf
        block: |
          CgroupMountpoint=/sys/fs/cgroup
          CgroupAutomount=yes
          ConstrainCores=no
          ConstrainRAMSpace=no
        create: yes
        state: present

    - name: Enable slurmd
      systemd:
        name: slurmd
        enabled: yes

    - name: Start slurmd
      systemd:
        name: slurmd
        state: started