---
- hosts: all
  become: true
  vars:
    docker_channel: stable
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
    vars:
        packages:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg-agent
            - software-properties-common
            - python3
            - python3-pip

  - name: Add an apt signing key for docker
    apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

  - name: "Add apt repository for docker channel: {{ docker_channel }}"
    apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} {{ docker_channel }}
        state: present

  - name: Install docker and its dependencies
    apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
    vars:
        packages:
            - docker-ce
            - docker-ce-cli
            - containerd.io
    notify:
        - docker status

  - name: Add vagrant user to docker group
    user:
        name: vagrant
        group: docker

  - name: Enable docker swarm
    command: docker swarm init --advertise-addr {{ node_ip }}

  - name: Generate join command
    shell: docker swarm join-token worker | grep 'docker swarm'
    register: join_command

  - name: Copy join command to local file
    copy:
      content: "{{ join_command.stdout_lines[0].strip() }}"
      dest: /shared/join-command

  handlers:
    - name: docker status
      service: name=docker state=started
