---
- hosts: masters
  gather_facts: False
  become: True
  tasks:
    - name: Prepare ambari repo
      get_url: url=http://public-repo-1.hortonworks.com/ambari/ubuntu16/2.x/updates/2.5.1.0/ambari.list dest=/etc/apt/sources.list.d/ambari.list 

    - name: Install ambari
      apt: name=ambari-server state=present update_cache=yes allow_unauthenticated=yes

    - name: Setup ambari - directories
      file: path=/var/lib/ambari-agent/data state=directory

    - name: Setup ambari
      run_once: true
      command: ambari-server setup -s

    - name: Ensure ambari-server is up
      service: name=ambari-server state=started enabled=yes
