apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Applications to support cluster functionalities
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  sourceRepos:
  - '*'