apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: cluster-apps
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.10.1
    helm:
      parameters:
        - name: serviceAccount.name
          value: ingress-nginx-sa
    chart: ingress-nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  